### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#1]
There are some things i noticed should be there in plugin and recommendations are below:

1. Let users set Min & Max amount for donations. (Can use other plugin for min, max but it would be great if it integrates into one single plugin (this plugin))

2. Let user give a parameter to be used in “shortcode” for redirecting users to custom thank you page after successful payment.

Please dont take these two things for granted.

I know these will and are very must for most of the users.

This plugin would become a multi-purpose plugin after integrating these two things.

Please consider these.

God bless you. I am in love with this plugin.

Really awesome.

**Comment by jonas-hoebenreich** [comment]
Hi Arun,

I am very happy that you like my plugin so much.

1. In the general settings you can set a minimum and maximum amount, which then applies to all projects. However, when I wanted to create the screenshot below, I noticed that the settings page is not displayed properly. I already found the bug and will push an update in the next minutes.
![image](https://user-images.githubusercontent.com/64426524/136686512-ea7dc130-deb9-4346-b787-f727d78ce8d6.png)
2. There are already many plugins to customize the thank you page, for example NextMove Lite (or just search for "woocommerce thank you"). That's why this was not a prio for the initial release. In the long run, I think that a customizable thank you page for fundraising campaigns is a good idea.

Thank you for being an early adopter of Donation Platform for WooCommerce. I'm looking forward to adding new features and improvements.
Kind regards from Germany,
Jonas

**Comment by jonas-hoebenreich** [comment]
#https://github.com/jonas-hoebenreich/wc-donation-platform/commit/e3264864f0182c69b23676fd90b30feadf388567

**Comment by procontentxyz** [comment]
[wcdp_donation_form id="12" button="0" popup="1"]

this is not working, in storefront theme by woocommerce.

i think its plugin issue not theme. could you check please.

**Comment by jonas-hoebenreich** [comment]
You can use the following code to redirect to another page:

```
add_action( 'template_redirect', function() {
	global $wp;
	if ( is_checkout() && !empty( $wp->query_vars['order-received'] ) ) {
		wp_redirect( 'https://example.com' );
		exit;
	}
});
```
I recommend the following plugin to add custom code to your website: https://wordpress.org/plugins/code-snippets/

The problem with the shortcode parameter is that the thankyou URL is not specified in the donation form, but by WooCommerce internally when processing the order. So it is difficult to pass a parameter from the shortcode accordingly.

Your use case also seems quite special to me. Probably it is easier to adapt the above code to cover the different URLs.

At the moment I think the following feature is sufficient for most users and can be implemented well:
In the General Settings you can specify a Thankyou URL. There is also a new shortcode that allows you to display donation specific content, e.g. the name or donation amount: [wcdp_thankyou field="first_name"] or [wcdp_thankyou field="payment_method"]
What do you think about it?
