### ISSUE TITLE
How can i pass addtional hidden custom meta in donation checkout form, and show on thank you page after that

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#11]
How can i pass addtional hidden custom meta in donation checkout form, and show on thank you page after that

**Comment by jonas-hoebenreich** [comment]
This seems to me to be more of a WooCommerce question and less specific to Donation Platform for WooCommerce.
What exactly are you trying to accomplish?

**Comment by procontentxyz** [comment]
I want to send a custom input value to checkout form ... And save it as order meta on Order placed.


How to paas this in Popup donation form...

**Comment by jonas-hoebenreich** [comment]
Maybe take a look at this plugin: https://wordpress.org/plugins/woo-checkout-field-editor-pro/
New fields can be hidden by CSS and can be filled automatically by JavaScript

**Comment by procontentxyz** [comment]
Can i pass value from product page to checkout page in popup donation form....provided by your donation plugin.

🤔

**Comment by jonas-hoebenreich** [comment]
I'm afraid I don't understand what exactly you want. Could you please explain step by step what you want and what exactly should happen?
The popup is not different from any other donation form, only that the corresponding container is adjusted accordingly via CSS.

**Comment by procontentxyz** [comment]
Okk ... Let me simplfy the conversation


Lets say i add this url in anchor tag:

example.com/product-name/?custom_meta=value#wcdp-form


Then, on click above link, it should open donation form in pop up right ?


Now question is.... Will it pass custom_meta query argument in checkout page .... from product page.


So that it got save as hidden input field on checkout after order placed?

**Comment by jonas-hoebenreich** [comment]
No, you would have to implement that yourself. The URL parameter attribute_xxx (https://wcdp.jonh.eu/documentation/usage/url-parameters/) refers exclusively to individual attributes of variable products.

Example: You create a variable product with the custom meta "project" with the possible values "conservation" or "planting", so that the supporter can choose which project he wants to support:
![image](https://user-images.githubusercontent.com/64426524/150974844-a240a3ab-847c-426f-b4c4-c30124e676e5.png)
https://wcdp.jonh.eu/projects/variable-product-attribute-demo/

You can now preselect the buttons with the following URL parameters:
https://wcdp.jonh.eu/projects/variable-product-attribute-demo/?project=Planting&attribute_project=Planting
https://wcdp.jonh.eu/projects/variable-product-attribute-demo/?project=Conservation&attribute_project=Conservation
If any other parameter is used, it is simply ignored.

What you want is not part of Donation Platform for WooCommerce or WooCommerce. If you want this functionality, you need to find an appropriate plugin or implement it yourself.

**Comment by procontentxyz** [comment]
Ok 🥲
