### ISSUE TITLE
Product data tab not working

### ISSUE THREAD

**Issue by Manusharavishan** [jonas-hoebenreich/wc-donation-platform#28]
Wordpress  and woocommerce latest version not working product data tab
![45a5d1asd](https://user-images.githubusercontent.com/72959495/213905408-0c0558fe-dbb0-496a-ab86-f6bbfc287c0e.PNG)
![5as4d55asd](https://user-images.githubusercontent.com/72959495/213905410-806224e2-cca4-4fae-a4c4-713e78e4845c.PNG)

**Comment by Manusharavishan** [comment]
Wordpress version  - 6.1.1
Wc version - 7.3

**Comment by jonas-hoebenreich** [comment]
Hi Manusharavishan,

please excuse the problem. I have already [fixed the bug](https://github.com/jonas-hoebenreich/wc-donation-platform/commit/2b659d3bfb45c5a254fd0812b806e28d307977a4), it will be rolled out with the next update of Donation Platform for WooCommerce. In the meantime, I recommend that you either manually update the plugin via [the latest version on GitHub](https://github.com/jonas-hoebenreich/wc-donation-platform/archive/refs/heads/main.zip) or update your php version. (I suspect the problem occurs because your server is using an outdated and unmaintained version of php, so for security reasons alone, upgrading would be advisable).

Best regards
Jonas
