### ISSUE TITLE
translate the plugin 

### ISSUE THREAD

**Issue by khawala** [jonas-hoebenreich/wc-donation-platform#33]
i need to translate the plugin 
how can i do that?

**Comment by jonas-hoebenreich** [comment]
Please refer to the following guide: https://wcdp.jonh.eu/documentation/usage/internationalization-localization-translation/

**Comment by khawala** [comment]
sir i try with this plugin as you mention but the translation doesn't appear i'm sure that i click on the sync icon
![image](https://user-images.githubusercontent.com/43215372/215939829-21d19ae1-a37c-487d-8d4e-d1a378481a67.png)

and i also need to know why the shortcut doesn't work with me 
![image](https://user-images.githubusercontent.com/43215372/215939459-dbcaf987-0ef0-4e5b-b79b-66bd790d405b.png)
it's appear as empaty page 

and is there any way to add quic donate button in my site

**Comment by jonas-hoebenreich** [comment]
"Coose an amount" & "Your Contribution" are set in the plugin's settings page.
Please also make sure that you translate the correct strings, e.g the string `"Choose an amount" Title Text` is used in the backend and not in the frontend of the plugin.
If you cant the the donation form it means that the styles are not loaded correctly. Please update and refresh the page.

**Comment by khawala** [comment]
I'm sure sir that i translate the correct word

Is there any way to add more than one donation form in the page?

**Comment by jonas-hoebenreich** [comment]
Thanks for your reply.
As soon as you have saved a different string in the Donation Platform for WooCommerce settings at example.com/wp-admin/admin.php?page=wc-settings&tab=wc-donation-platform, this string will be used instead of the default string. What language is your website set to? In the screenshots it seems to me to be English.
And please excuse me, in the screenshot the wrong strings are visible, so I had wrongly concluded that this could be the reason.

Since WooCommerce and other plugins don’t assume that there are multiple checkouts on a page, you might run into problems otherwise. 

Best regards
Jonas
