### ISSUE TITLE
Divi integration causes shutdown

### ISSUE THREAD

**Issue by destrecht** [jonas-hoebenreich/wc-donation-platform#36]
**Describe the bug**

Divi allows you to change woocommerce elements.
When I use it to change the button color, I get an error.

"Only one donation form per page allowed"

All I did was enable DIVI. 
  

 

**To Reproduce**
1. Go to "enable visual builder"
2. hover over module
3. change button
4. Save
5. close visual builder. 

If I got rid of steps 2 and 3 the result would be the same.
 

**Expected behavior**
It should allow me to edit the button and behave normally.

**Error Log**
"Only one donation form per page allowed"

**Screenshots**
<img width="395" alt="image" src="https://user-images.githubusercontent.com/13119867/224045401-b82fe7d0-1e53-4ad6-8c82-5545c9ac79af.png">

**Device (please complete the following information):**
 - Device: Windows laptop
 - OS: Windows 11
 - Browser Brave
 - Version 1.48
v

**WordPress Environment**
<img width="395" alt="image" src="https://user-images.githubusercontent.com/13119867/224046727-1b3b4bdd-14f4-4112-aa2b-807fd788b8a4.png">

**Comment by jonas-hoebenreich** [comment]
Hi destrecht,

thanks for reaching out.
Unfortunately I can't debug the problem very well, because I don't have a license for divi. The error message occurs whenever the function `wcdp_donation_form` is called twice within a page load. You would need to contact the divi support team as to why this is the case.
If you want, I can implement a workaround that allows to insert as many donation forms as you want on one page. Would that help?

Best regards
Jonas
