### ISSUE TITLE
Progress bar not update

### ISSUE THREAD

**Issue by mytranspro** [jonas-hoebenreich/wc-donation-platform#42]
Hi, 
re already received the donation and the order status changed to completed, but still no update add progress bar. It still remains 0.
please help

**Comment by jonas-hoebenreich** [comment]
Calculating the sum of donations is actually quite resource intensive especially on busy sites. Donation Platform for WooCommerce therefore uses some strategies to improve performance. First of all, the amount is only calculated once an order changes its status to/from completed. In order to further reduce the load on the server (or more precisely the database) during peak loads, this calculation is performed at most once every 30s. To clean up any inconsistencies, the amount is also recalculated every 6h.
So if the amount is not updated directly, the problem should resolve itself within 6h (or if a new donation is processed in the meantime).
If you use a caching plugin (e.g. WP Super Cache or W3 Total Cache), the page itself may also be cached.
