### ISSUE TITLE
How to change "Learn more" button text to "Read more"  on archive pages????

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#5]
How to rename "Learn more" button text to "Read more"  on archive pages????

Also, Could you provide options in setting to change these words...... (Learn more, Related projects, etc)

**Comment by jonas-hoebenreich** [comment]
Just use the following filter:
`add_filter('woocommerce_product_add_to_cart_text', function(){
	return 'Read more';
}, 11 );`
Since this functionality is already implemented by numerous plugins (e.g. https://wordpress.org/plugins/woo-custom-add-to-cart-button/), I think I will probably not implement this feature for now.

**Comment by procontentxyz** [comment]
thank you it works :)
