### ISSUE TITLE
I am wondering if its possible :)

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#6]
Hi sir, I hope you are doing well!

How can we replace "Learn more" button with "Donate now" on archive pages (loops), 

accept donation directly from archive pages without going to single product page.

I have a use case where accepting donation directly on archives is the main need.

Please guide how to accomplish this.

Thank you for this awesome plugin software.

Its like another woocommerce like extension for WordPress.

God bless you !

**Comment by jonas-hoebenreich** [comment]
Hi,
thanks for your message.
Since WooCommerce internally assumes that there is a maximum of one checkout on a page, it is not possible to put multiple donation forms on one page.
However, you can create as many buttons as you like that link to the checkout page and pass the respective donation parameters via POST/GET.
e.g. a link could look like this: https://wcdp.jonh.eu/checkout/?postid=3515&donation-amount=1000&wcdp-donation-amount=1000&variation_id=3517&attribute_designate-to=Stet+Clita+Kasd
Then you could create multiple buttons with different labels and then adjust the 'donation-amount' & 'wcdp-donation-amount' parameters accordingly.
Many greetings,
Jonas

**Comment by procontentxyz** [comment]
Cannt we show checkout page in pop up???

**Comment by jonas-hoebenreich** [comment]
No, for this you would have to disable the iframe protection of WooCommerce and your payment gateways. That would be very time-consuming.
